package com.grievance.model;

import java.sql.Timestamp;

/**
 * Represents a user in the Grievance System (maps to the 'users' table).
 */
public class User {
    private int id;
    private String username;
    // NOTE: In a real app, never store or pass raw password like this.
    // For this CLI demo, we include it for simplicity in the login process.
    private String password; 
    private String role; // ENUM: ADMINISTRATOR, USER, GRIEVANCE_MANAGER
    private Timestamp createdAt;

    // Default Constructor
    public User() {}

    // Constructor for creating a new user (ID and timestamp generated by DB)
    public User(String username, String password, String role) {
        this.username = username;
        this.password = password;
        this.role = role;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "User [ID=" + id + ", Username=" + username + ", Role=" + role + "]";
    }
}
